#!/bin/bash
set -e


[ -e ../template/zfunctions.sh ] && source ../template/zfunctions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control lxqt
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxqt-settings.install \
    > ./debian/${CODENAME_SAFE}-lxqt-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxqt-settings.postinst \
    > ./debian/${CODENAME_SAFE}-lxqt-settings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxqt-livesettings.install \
    > ./debian/${CODENAME_SAFE}-lxqt-livesettings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxqt-livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-lxqt-livesettings.lintian-overrides

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxqt-livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-lxqt-livesettings.preinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxqt-livesettings.service \
    > ./debian/${CODENAME_SAFE}-lxqt-livesettings.service


## templating

[ -d ./etc ] && rm -rf ./etc
cp -a ../template/etc .


sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/etc/xdg/pcmanfm-qt/lxqt/settings.conf \
    > ./etc/xdg/pcmanfm-qt/lxqt/settings.conf

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/etc/xdg/lxqt/lxqt.conf \
    > ./etc/xdg/lxqt/lxqt.conf


grub_template lxqt


exit 0
