#!/bin/sh
# postinst script for #PACKAGE#

set -e

if [ -f /etc/default/distro ]; then
    . /etc/default/distro
fi

case "$1" in
    configure)
        ## dconf ##
        cp -af /usr/share/wintersky-lxqt-settings/etc/dconf          /etc
        ## gtk-2.0 ##
        cp -af /usr/share/wintersky-lxqt-settings/etc/gtk-2.0        /etc
        ## NetworkManager ##
        cp -af /usr/share/wintersky-lxqt-settings/etc/NetworkManager           /etc
        ## iwd ##
        cp -af /usr/share/wintersky-lxqt-settings/etc/iwd                      /etc
        ## skel ##
        cp -af /usr/share/wintersky-lxqt-settings/etc/skel/config    /etc/skel/.config
        cp -af /usr/share/wintersky-lxqt-settings/etc/skel/dmrc      /etc/skel/.dmrc
        cp -af /usr/share/wintersky-lxqt-settings/etc/skel/gitconfig /etc/skel/.gitconfig
        cp -af /usr/share/wintersky-lxqt-settings/etc/skel/gitignore /etc/skel/.gitignore
        cp -af /usr/share/wintersky-lxqt-settings/etc/skel/Xdefaults /etc/skel/.Xdefaults
        ## xdg  ##
        cp -af /usr/share/wintersky-lxqt-settings/etc/xdg            /etc
        ## settings ##
        dconf update
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
